skype :
  default : "#username/$a1b2c3def"
  foobar  : "#foobar/$asdf3413dvb"
gyazz : 
  - wiki  : test
  - wiki  : shokai
    user  : username
    pass  : password
    skype : foobar
ignore :
  - .書込認証
  - .完全認証
  - .passwd
